name: "Bug Report"
description: "Create a report to help improve"
title: "[BUG] "
labels: ["bug"]
assignees:
  - mylinuxforwork
body:
  - type: markdown
    attributes:
      value: "## Bug Report\nPlease fill out the details below."

  - type: input
    id: bug_description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the behavior."
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false

  - type: dropdown
    id: distribution
    attributes:
      label: "Distribution"
      description: "Select your Linux distribution."
      multiple: false
      options:
        - "Arch Linux"
        - "EndeavourOS"
        - "Manjaro"
        - "Other (please specify below)"
    validations:
      required: true

  - type: input
    id: other_distribution
    attributes:
      label: "If Other, specify"
      description: "Enter your Linux distribution if it was not listed above."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
    validations:
      required: false

